meta_product_name: "GLADIUS"
meta_title: "Gladius - Manage your trainings"
meta_description: "A web tool making creating, planning, tracking and sharing its training easy and fun!"
meta_image: "gladius-image.jpg"                           # Une image dans votre dossier app/assets/images/

